config/routes.rb
Rails.application.routes.draw do

  root 'listings#index'

  # resources :videos
  # resources :photos
  resources :listings

end

app/models/listing.rb
class Listing < ActiveRecord::Base

  mount_uploader :photo, PhotoUploader
  mount_uploader :video, VideoUploader

  has_many :photos, :dependent => :destroy
  has_many :videos, :dependent => :destroy

  accepts_nested_attributes_for :photos, :videos, :reject_if => :all_blank, allow_destroy: true

  def photo_changed?
  end

  def video_changed?
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :listing

  mount_uploader :image, PhotoUploader

end

app/models/video.rb
class Video < ActiveRecord::Base

  belongs_to :listing

  mount_uploader :vid, VideoUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def index
    @listings = Listing.all
  end

  def show
    @listings = Listing.all
    @listing = Listing.find(params[:id])
    @images = @listing.photos
    @videos = @listing.videos
  end

  def new
    @listing = Listing.new
    @listing.photos.build
    @listing.videos.build
  end

  def edit
    @listing = Listing.find(params[:id])
    @listing.photos.build
    @listing.videos.build
  end

  def create
    @listing = Listing.new(listing_params)
    if @listing.save!
      redirect_to @listing
    else
      raise
      render action: 'new', notice: 'Something went wrong, Listing was not saved!'
    end
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.update(listing_params)
      redirect_to @listing
    else
      render action: 'edit', notice: 'Something went wrong, please try again...'
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    redirect_to action: 'index', notice: 'Listing was successfully deleted.'
  end

  private
  def set_listing
    @listing = Listing.find(params[:id])
  end

  def listing_params
    params.require(:listing).permit(:business_name,
                                    :business_number,
                                    photos_attributes: [:id, :image, :title, :listing_id, :_destroy],
                                    videos_attributes: [:id, :vid, :title, :listing_id, :_destroy]
                                    )
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save!
      redirect_to @photo, notice: 'Listing was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update
      redirect_to @photo, notice: 'Photo was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to photos_url, notice: 'Photo was successfully deleted.'
  end

  private

    def set_photo
      @photo = Photo.find(params[:id])
    end

    def photo_params
      params.require(:photo).permit(:listing_id, :title, :image, :image_cache)
    end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
    @videos = Video.all
  end

  def new
    @video = Video.new
  end

  def edit
    @video = Video.find(params[:id])
  end

  def show
    @video = Video.find(params[:id])
  end

  def create
    @video = Video.new(video_params)
    if @video.save!
      redirect_to @video, notice: 'video was successfully uploaded.'
    else
      render action: 'new'
    end
  end

  def update
    @video = Video.find(params[:id])
    if @video.update
      redirect_to @video, notice: 'video was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    redirect_to videos_url, notice: 'video was successfully deleted.'
  end

  private

    def set_video
      @video = Video.find(params[:id])
    end

    def video_params
      params.require(:video).permit(:listing_id, :title, :vid, :video, :vid_cache)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Odeskjob</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/listings/edit.html.erb
<%= render 'listings/shared/form' %>

<% content_for :javascript do %>
<% end %>

<%= link_to 'Show Listing', @listing %>
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<table class="uk-table uk-table-striped">
  <thead>
  <tr>
  <th>Listing Name</th>
  <th>Active Citations</th>
  <th>Pending Citations</th>
  <th>Problems</th>
  </tr>
  </thead>
  <tbody>
  <% @listings.each do |listing| %>
    <tr>
    <td><%= link_to "#{listing.business_name}", listing %></td>
    </tr>
  <% end %>
  </tbody>
  </table>

<div class="uk-grid">
  <div class="uk-width-medium-1-2">
    <%= link_to 'New Listing', new_listing_path, class: 'uk-button' %>
  </div>
</div>

app/views/listings/new.html.erb
<%= render 'listings/shared/form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/shared/_form.html.erb
<%= form_for @listing, html: { multipart: true}  do |f| %>

<%= f.label :business_name, 'Business Name' %>
<%= f.text_field :business_name, :autofocus => true %>

<%= f.label :business_number, 'Business Number' %>
<%= f.text_field :business_number %>

<%# Image Upload Logic Goes Here %>
<%# Video Upload Logic Goes Here %>

<%= f.submit %>

<% end %>

app/views/listings/show.html.erb
<% content_for :javascript do %>
  <%= javascript_include_tag "https://cdn.sublimevideo.net/js/ulrkjov4.js" %>
<% end %>

<h1><%= @listing.business_name %></h1>
<h1><%= @listing.business_number %></h1>

<% @listing.videos.each do |video| %>
    <video class="sublime" data-settings="uid:demo-responsive-fit-resizing; autoresize:fit;" title="<%= @listing.business_name %> Video" width="640" height="360" preload="none">
      <source src="<%= video.vid.url %>">
    </video>
<% end %>

<% @listing.photos[0..3].each do |photo_image, i| %>
    <%= image_tag(photo_image.image.url(:thumb), class: 'uk-thumbnail') %>
<% end %>


<ul>
  <li><%= link_to 'Back', listings_path %></li>
  <li><%= link_to 'Edit', edit_listing_path(@listing) %></li>
  <li><%= link_to 'Delete', @listing, method: :delete, data: { confirm: "Are you sure you want to delete #{@listing.business_name}?" } %></li>
</ul>